services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native client
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  crontab-ui:
    image: alseambusher/crontab-ui:latest
    container_name: crontab-ui
    ports:
      - "8000:8000"
    volumes:
      - ./crontabs:/crontab-ui/crontabs
    environment:
      - HOST=0.0.0.0

  scrapy:
    build: .
    container_name: scrapy-app
    volumes:
      - .:/app
    depends_on:
      - clickhouse
    working_dir: /app
    # You can override the command in crontab-ui to run spiders
    command: ["bash"]

volumes:
  clickhouse_data:
